### ISSUE TITLE
Unable to add rss feed

### ISSUE THREAD

**Issue by rp1231** [chezhe/aleph#12]
I've been trying to add this url as an rss feed but it doesn't seem to be working.....

https://www.theverge.com/rss/index.xml

Thanks

**Comment by rp1231** [comment]
I'm using the windows version.
It didn't work in the previous version and doesn't seem to be working in the latest version as  well.

**Comment by chezhe** [comment]
Thanks for feedbacks.
I add it to TODO.
It seems different RSS sources have different format.
verge like:
![Screen Shot 2022-06-24 at 14 15 33](https://user-images.githubusercontent.com/2902414/175474462-34802d24-6258-4abb-856c-68793228134c.png)
Others like this:
![Screen Shot 2022-06-24 at 14 16 39](https://user-images.githubusercontent.com/2902414/175474519-60d52e57-bcbb-4fe1-9a9d-894260392979.png)

On Aleph, I only parse the second one which contents wrapped in **channel**.

I will fix it soon.

**Comment by chezhe** [comment]
@rp1231 Try 0.7.0 version

**Comment by rp1231** [comment]
@chezhe 
It's working now.
Thanks
